language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "hVducuLOXhc8DGQNFIPjZpupMKVdqTRkij2U4dPJEkbH0324Df7lvd2AieI+BLtukDlCFqkIbBwDLNs6tJYMhGNH9aykbj+QFAdG5emhYKd8nT2mEXquCR4XdHFBhkLOohC3U47ZEy0BkWy2hXsNgN7WZEwpcCPEoGcemAietljdRJ8/tA/hEyj8GPpy830rRqWSEQQYk7sEcpHFXIhW4DWP4fY0fMsM6TPPiUL/42r6jKh54aGJEe/bFNS3v3nGxS3s5dhwGASbH7My/ks4bc2BuSv8M2+fNJyjVUaORF8WFlpa7Rk+QJhF81fCDphHdoyoHvySxkln8sX0fpviG0YydGdJTfoGgOcclkbM0nOgGVQIfsPl1yrNBHdfbfM9uALRp09X6scCS4O4piZWgZX2grAC4XK7a4m62naG+K3URefLHTLn/xS2It7A13XbXPInAgPRRm6jv6Qn6hdbF6F0w4ff/wmvVkBFXuecIfh42R41H2ktRfICamTPk/vDXyzcZqgFMDDZ6LyFSC95ZzMiipBIMmTPi0tCAfLIekGfw/ZYTzz8Ow0x3pJoi1ba1B9XBc8keVVrx3J24m+/zzYQdRyPf/IwalRC/4jQzkPCL1nO854yHCGrgZUrhGkHB3mNhJryOdSldH9QnUdUL0tZSxEGQVPJtenG0QoIWrQ="
