language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
- "./ci/doc.js"
after_success:
- publish-if-needed
env:
  global:
    secure: NSvDw+zo1nVfvze7W9WQbh7C5CUexr3S1gtttPKcKusSdIDd7M4qvzJHZe28njIdnrDPjRZQkv/1DIXwTr90qDHDzmaqdtORJud2X9+y1Cw3gl9/3YNuADdjJSqbvx7Y3wop+hpaKPMQwvnpbMvuK6emkw9xmCybmR86V5aAoyaqdvfXzFEr+1YxUcCBSxUZzE0i4mYx3OsmRTAPaxblOiB8RO8F8rX+gTvSpiggW0IBUO+ifnG2EHjRwMtJ6A1RtNPHZWKyCvvN5P5pE7V4HMpRK07Mhaf7Pf4SONASvm4NleoRkQiOdZW+z4TTHbubhGo9SaRTpuybTl0QFFeVXmqC3rUdqtgcFsoux1u5ds2Tb2hhqRvhVDzdLGaAEwXqZExDANqWVKCy/lLGGSSsehi3zeRO37m1FL7IP2yB6IpnYuQxGzjMge03i4KZS2A2G5msw5DB9qVhbvz3cEomYAzpcbXeLAcg54BU/pzWjNgweas51vXPJ5dfBRKRbz8PgucVDKZ+mbtmjVKRBhZoeKtbbHoEHpX63E8jekaqx5XYs96wSKSseSy9ohzg3E33tOrB9lhgRDkm3apySwfooIdHQv9evRk+VNcmDPhb0moJfQXG0wsCOYgLIi8hpZsjsUa60yI1BJrnkTB7FIvff3RuGIic38zKVnQarz+3nrA=
