language: node_js
node_js:
- '6'
before_install:
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
install:
- npm install -g jsdoc mocha
- npm install
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  secure: "tc+War/Mx9VUarg0IYAxQwng3cDEjQhCs+zLItkPE3HVj/efgxEVhxA9M7fE/IRwCGuLAUimGsdmy8eovqRp56M9lV+mLvdV0Hr4h34LkypS0A4Ukt/iDL42U5VjhNQGI1mraaOwRdARR89cc2MvguAMDQRbiuCUBBwcRXXSzyMGpXs1HmX8mcHnMKTlyK1nltyKpqgjcx9F3hexjdYHj7WSgXXFfZKrFo4gzSgAAowEhzxGJX6Q4Qm7ASRyUtXhkdoXuorDr1i3t/8r+r+kX7uN4XB3xjJ/gZ9YtVGbrnDN+QBNGfyx1lPHAkXFlDVjsRA5Kk5Sp27DXZSyzNpwSbTLtetq1wupuyX5PLtMaOAGC0ELJCuT577CAJsgV3Y7DQhhzJwZsDSKQwRXwBGOfFi6N2WY3zhTH/hSy0E6HZW4mQeqjiOa9d0kI3L7lpTrhAs9iTTqVsHEUBzwfWeSGhnarof+9hSfp+avpXwlShRZs+6ckuV6MG/Y7yNqIF0E9BLoc2Qpe5QlUX6OvP8unhnZ96A01diSBqvUu5ntX31TP1zkVp7YgEtoFXCEbAs6o6TnqJmKg/XwZ/JZfz2pJIsiLcUAgoID6e8fPeEMYvZ0TG7KhlLBE3l4RZCPcUQlqtJWk3o133XFre6rOHa3/S39iNSaFiYZGUAthAyp9JM="