language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "0jyqBuy2bAcu39xFwOUJjY7iwmG0wTgwYaLfP1LbF/Jd8hRtaZUyoFS/XjJ6zhrmA35aKCs7QI4stNPvAgb0YoqeTXcxcKJ/Kx75YSb/4q7l7w6kXbAC+UgebZINxGI/vV8f5nTFPzQSNklRuuTfMmaUkeFylJpZvbCMXd8GbF1P72vS2v8svBTNsfJExtGzl25LEE4PVN6LUbIMqe/e+6y1UtuuOnEIdxNFjZaANiAcMV0aVwmO3FDiD1AbhNvoB/RJw+BOZSBBb3KAoI+KKruWXg4f0J8ybcFjo3FHPOSlRfmikTkQGWvBLz8eH361Zt/JWZnIosLHBT+4HDgRdF+QDyRuf+fLOZqSSarMzrWz37klrgkemy2hPvKt1vNfH0/5zff9A8qcNqo+xI8gCV8X579pMkLiXWS9mPnEcth3CJJrLQ15DR10kpfjPt3Y2HOB0lgP+QcFA6fujSvxneeiGzAJDYw2mXo8uhtL7YNAKxo/2ns02ked/d5eYS5I+KcZZHyBFJpt8zsgzj/A0PCkhidYNcG4NKItFJ+vAbiDJFX2twh3Nm2chBMpV+5BPEz/M2c7EheSYby8ORUJPgYqWBg0NzShcivg8bGg9LfTdbbSDLzzAeOzLFYB0H6VPWyn+uYgHU/r3qkumIv5r7NaSh4QdRDt5U1txRfjT5w="
